[version]
current = "0.0.0"

# Example of a semver regexp.
# Make sure this matches current_version before
# using tbump
regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  (\.
    (?P<extra>.+)
  )?
  '''

[git]
message_template = "Bump to {new_version}"
tag_template = "v{new_version}"

# For each file to patch, add a [[file]] config section containing
# the path of the file, relative to the tbump.toml location.
[[file]]
src = "pyproject.toml"

[[file]]
src = "gpdsp/__init__.py"
search = '__version__ = "{current_version}"'

[[field]]
# the name of the field
name = "extra"
# the default value to use, if there is no match
default = ""
