#!/usr/bin/env bash

native_processing(){
    echo "---- Executing bldr"
    source /usr/local/bin/bldr_env.sh
    echo "-- Configure container environment"
    #bldr self configure --twine
    # Useful visual confirmations
    echo "-- Checking configuration settings"
    echo "      PATH = "$PATH
    echo "   WORKDIR = "$(pwd)
    # Set up the path to the language-specific implementation
    export LOCAL_EXEC="/usr/local/bin/bldr_"$BLDR_EXEC
    echo "LOCAL_EXEC = "$LOCAL_EXEC

    # If this is launched from the incorrect subdirectory,
    # the script will error out.
    pushd $BLDR_EXEC/$BLDR_TARGET
    retVal=$?
    if [ $retVal -ne 0 ]; then
        echo "Failed to CD into "$BLDR_EXEC/$BLDR_TARGET
        exit $retVal
    fi
    # Execute the specific script for the target language model
    source $LOCAL_EXEC
    # Return to the working directory
    popd
    echo "---- Exiting bldr"
}

run_docker() {
    echo "Launch linux environment"
    docker run --rm -v $(pwd):/home/dzbld/work  dzbld
}

echo $OSTYPE
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
        echo "Linux environment"
        native_processing 
elif [[ "$OSTYPE" == "darwin"* ]]; then
        echo "Mac OSX environment"
        run_docker  
fi