#!/usr/bin/env python3
"""
Module docstring
"""

import json
from pathlib import Path


class Specs:
    """
    Class docstring
    """

    def __init__(self, spec: Path):
        self._src: Path = None
        self._trg: Path = None
        self._selects = {}
        self._spec: Path = spec
        # self._sourceset = None
        # self._targetset = None
        self._copyset = []

        self.read_specs()

    def read_specs(self):
        """
        Method docstring
        """
        if self._spec is not None:
            with open(self._spec, encoding="utf8") as fp:
                data = json.load(fp)
                self._src = data["source"]
                print(self._src)
                self._trg = data["target"]
                print(self._trg)
                self._selects = data["selections"]
                print(self._selects)

    def process_specs(self):
        """
        Method docstring
        """
        for genre in self._selects:
            print(f"Genre : {genre}")
            print(self._trg)
            gpath: Path = Path(self._trg, genre)
            print(gpath)
            gpath.mkdir(parents=True, exist_ok=True)
            for artist in self._selects[genre]:
                print(f"\tArtist : {artist}")
                apath: Path = Path(gpath, artist)
                apath.mkdir(parents=True, exist_ok=True)
                if self._selects[genre][artist][0] == "*":
                    srcpath = Path(self._src, genre, artist)
                    outstr = (
                        f'rsync -avp --delete --exclude=".*" "{srcpath}/" "{apath}/"'
                    )
                    self._copyset.append(outstr)
                else:
                    for album in self._selects[genre][artist]:
                        print(f"\t\tAlbum : {album}")
                        albpath: Path = Path(apath, album)
                        albpath.mkdir(parents=True, exist_ok=True)
                        srcpath = Path(self._src, genre, artist, album)
                        outstr = f'rsync -avp --delete --exclude=".*" "{srcpath}/" "{albpath}/"'
                        self._copyset.append(outstr)
        print(self._copyset)
        with open("collate.sh", "w", encoding="utf8") as fo:
            for item in self._copyset:
                fo.write(f"{item}\n")


if __name__ == "__main__":
    spex: Specs = Specs(Path("acollrc"))
    spex.process_specs()
